create table if not exists public.gtc_course_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  course_code text not null,
  name text not null,
  phone text not null,
  email text not null,
  region text not null,
  applicant_type text not null,
  organization text,
  experience text,
  message text,
  status text not null default 'new',
  source text not null default 'gtc-web',
  admin_note text
);

alter table public.gtc_course_applications enable row level security;

drop policy if exists "gtc course application public insert" on public.gtc_course_applications;
create policy "gtc course application public insert"
on public.gtc_course_applications for insert
to anon, authenticated
with check (status = 'new' and source = 'gtc-web');

-- 접수 내용은 수파베이스 대시보드의 Table Editor에서 본부가 확인합니다.
-- 관리자 전용 웹 화면은 다음 단계에서 관리자 역할 테이블과 함께 연결합니다.
